name: $(TeamProject)_$(Build.DefinitionName)_$(Build.SourceBranch)_$(Date:yyyyMMdd)$(Rev:.r)

steps:
  - script: echo '$(Build.BuildNumber)' # outputs customized build number like project_def_master_20200828.1
  - task: DotNetCoreCLI@2
    displayName: Build Project
    inputs:
      command: 'build'
      projects: 'ConsoleApp1.sln'
  - task: CopyFiles@2
    displayName: Copy Binaries
    inputs:
      SourceFolder: 'ConsoleApp1/bin/Debug/net5.0'
      TargetFolder: '${Build.ArtifactStagingDirectory}/ConsoleApp1'
      Contents: 'ConsoleApp1.exe;ConsoleApp1.dll'