name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

steps:
  - script: echo '$(Build.BuildNumber)' # outputs customized build number like project_def_master_20200828.1
    displayName: Get Build.BuildNumber
  - task: MSBuild@1
    displayName: Build Project
    inputs:  
      solution: '**/*.sln'
      msBuildVersion: '16.0'
      clean: false